### ISSUE TITLE
Confirm about the license field

### ISSUE THREAD

**Issue by hare1039** [HubSpot/PlanOut.js#48]
Hi, I'm a member of cdnjs, and we want to add this library to our server.
Inside [package.json#59](https://github.com/HubSpot/PlanOut.js/blob/master/package.json#L59)
The license field is Facebook's `BSD-3-clause`.

Is this library is also `BSD-3-clause`?

**Comment by rawls238** [comment]
yup!

**Comment by hare1039** [comment]
Great! I'll add this library ASAP!
