### ISSUE TITLE
Running examples/experiment_verification.js leads to a `throw "IMPLEMENT setup"` error

### ISSUE THREAD

**Issue by ckuijjer** [HubSpot/PlanOut.js#63]
Running the example in _examples/experiment_verification.js_ leads to a `throw "IMPLEMENT setup"` error.

I've tried fixing this in pull request #62 by adding the `extend` method as also used in _sample_interpreter_es5.js_ and _sample_planout_es5_

**Comment by rawls238** [comment]
Ah I forgot about these, they must have not been updated in the update to 4.0. @mattrheault can you take care of this?

**Comment by mattrheault** [comment]
Fixed in https://github.com/HubSpot/PlanOut.js/pull/64
