### ISSUE TITLE
Safari hangs when using planout_core_compatible.js

### ISSUE THREAD

**Issue by amishyn** [HubSpot/PlanOut.js#65]
I have installed planout_core_compatible.js and using UniformChoice. It works good across all browsers except Safari (Mac OS 10.12.6, Safari 10.1.2). In safari is enters loop in randomIndexCalculation. Is it known issue ?

**Comment by mattrheault** [comment]
@amishyn yup this is a known issue for all browsers. I would recommend that you avoid using the core compatible bundle if possible... especially if you are going to evaluate experiment param values on the client side.

Out of curiosity, why did you choose the core compatible bundle instead of the default bundle?

From the docs:

> The planout_core_compatible.js bundle should be used only if you want your random operation results to match that of the results from other planout implementations (java, python, etc). The filesize of the planout_core_compatible.js bundle is fairly larger (by ~100kb) and random operations are processed slower.

**Comment by rawls238** [comment]
@mattrheault any ideas what the root cause is? Is it for all random ops?

**Comment by mattrheault** [comment]
Hrmm, I'm re-reading this now. While core compatible random ops are slower, I cannot get safari or any other browsers to hang indefinitely on a uniform choice, or any other op for that matter.

@amishyn would you mind sharing your experiment param / namespace code?

**Comment by amishyn** [comment]
Hi @mattrheault,

I've chosen compatible version because at the moment I'm in process of setting up experiments infrastructure and not sure where will I need it frontend/backend, most probably will need it on both. Thus as the safest version I selected compatible. Which turned out to be not the safest :-) When I switched to planout.js it works fine in safari. So I'm going to proceed with it.


 Here is the experiment https://gist.github.com/amishyn/4433c099bd2c895a6fc09bca9e430bf9

And here is the line when it stucked for me: https://github.com/HubSpot/PlanOut.js/blob/master/dist/planout_core_compatible.js#L4855

**Comment by mattrheault** [comment]
I ran the experiment you posted locally against the core compatible version and investigated a bit. Unfortunately, I was unable to break my browser (this time).

The line you are referring to @amishyn is from [BigNumber.js](https://github.com/MikeMcl/bignumber.js/blob/b12705646d76f8867861affe0646faaadbd3a55e/bignumber.js#L1751), which is a library the core compatible version uses to ensure the output of random operations are the same as the reference implementation of planout.

I will leave this issue open to reference & investigate further when I have more time.

**Comment by rawls238** [comment]
One really easy thing to try to fix this is to see if there is an update to BigNumber and simply update the version and see if this resolves the issue.
