### ISSUE TITLE
location.search breaks server-side usage

### ISSUE THREAD

**Issue by TimBeyer** [HubSpot/PlanOut.js#8]
In https://github.com/HubSpot/PlanOut.js/blob/9a97c92ed29526ca810153321e442646c6f3f53f/es6/lib/utils.js#L14 `location.search` is accessed, which I assume is for overriding test parameters based on the URL.  
Sadly this breaks usage on nodeJS since `window.location` is not available there.

For now I would propose to do a simple check whether it is available, but in the future it would probably be best if we could provide a hook for these overrides so that isomorphic applications can make use of this consistently.

**Comment by rawls238** [comment]
Good catch on this. Yea this is mainly used for testing experiment parameter overrides locally when using SimpleNamespace - I'm going to add some more information about overrides to the README. There are overrides that can be defined in the definition of the namespace itself which should play much nicer with node versus the localStorage/query parameter way of defining overrides.
